import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Box, Flex, Heading, Text, Image, Button } from "@chakra-ui/react";
import { NavbarComponent } from "@/components/elements/navbar";
import { PageContainerComponent } from "@/components/elements/pageContainer";
import { MyContext } from "@/context";
import { useContext } from "react";
import { homeText } from "@/assets/text";
import { CgPiano } from "react-icons/cg";
import { FaGamepad } from "react-icons/fa";
import { BsMusicNoteBeamed } from "react-icons/bs";

export default function Home() {
  const { language } = useContext(MyContext);

  return (
    <>
      <Head>
        <title>Samuel Vianna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavbarComponent />
        <PageContainerComponent>
          <Flex alignItems="center" justifyContent="center" mb={24} gap={8}>
            <Box maxW="700">
              <Heading>{homeText[language].greetings}</Heading>
              <Text my={8}>{homeText[language].intro}</Text>

              <Flex alignItems="center" gap={4}>
                <Text as="b">Hobbies:</Text>
                <CgPiano id={styles.hobbie1} />
                <FaGamepad id={styles.hobbie2} />
                <BsMusicNoteBeamed id={styles.hobbie3} />
              </Flex>

              <Button variant="outline" mt={8}>
                <a href={"cv.pdf"} download="samuel_vianna.pdf">
                  {homeText[language].button}
                </a>
              </Button>
            </Box>
            <Flex>
              <Image
                src="/eu.jpeg"
                alt="profile photo"
                borderRadius="50%"
                objectFit="cover"
                w={300}
                h={300}
              />
            </Flex>
          </Flex>
        </PageContainerComponent>
      </main>
    </>
  );
}
